name: CI pipeline
on:               # this is the pipeline trigger
  pull_request:
    types: [opened]
jobs:
  startup:
    name: Run startup script
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world from the startup script"
  build:
    name: Build pipeline task   # display name
    runs-on: ubuntu-latest      # runner
    needs: startup
    steps:
      - name: Comment on PR
        run: gh pr comment $PR_URL --body "Thanks for your PR. We will review shortly"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}   # 
      - name: Check for buttons
        run: ./.github/scripts/checker.sh
        env:
          FILE: ./src/components/Buttons.js